<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst;net8.0;net9.0-android;net9.0-ios;net9.0-maccatalyst;net9.0</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0;net9.0-windows10.0.19041.0</TargetFrameworks>
    <!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
    <!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>

    <AssemblyName>Plugin.StoreReview</AssemblyName>
    <RootNamespace>Plugin.StoreReview</RootNamespace>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <AssemblyFileVersion>1.0.0.0</AssemblyFileVersion>
    <Version>1.0.0.0</Version>

    <!-- NuGet -->
    <Authors>James Montemagno</Authors>
    <Copyright>Copyright Refractored LLC and contributors</Copyright>
    <IsPackable>True</IsPackable>
    <PackageId>Plugin.StoreReview</PackageId>
    <PackageProjectUrl>https://github.com/jamesmontemagno/storereviewplugin</PackageProjectUrl>
    <RepositoryUrl>https://github.com/jamesmontemagno/storereviewplugin</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>dotnet-maui;maui;plugin;review;storereview;android;ios;windows;maccatalyst</PackageTags>
    <IncludeSymbols>True</IncludeSymbols>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Title>Store Review Plugin for .NET MAUI, iOS, Android, MacCatalyst, and Windows</Title>
    <Description>Easily request a review or open the store page for your app.</Description>
    <Summary>Easily request a review or open the store page for your app.</Summary>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <DebugType>portable</DebugType>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    
  </PropertyGroup>

  <!-- iOS & MacCatalyst -->
  <ItemGroup Condition="$(TargetFramework.StartsWith('net')) == true AND $(TargetFramework.Contains('-ios')) != true AND $(TargetFramework.Contains('-maccatalyst')) != true ">
    <Compile Remove="**\*.apple.cs" />
    <None Include="**\*.apple.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
    <Compile Remove="**\apple\**\*.cs" />
    <None Include="**\apple\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
  </ItemGroup>
  <!-- Android -->
  <ItemGroup Condition="$(TargetFramework.StartsWith('net')) == true AND $(TargetFramework.Contains('-android')) != true">
    <Compile Remove="**\*.android.cs" />
    <None Include="**\*.android.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
    <Compile Remove="**\android\**\*.cs" />
    <None Include="**\android\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.Contains('-android')) ">
    <PackageReference Include="Xamarin.Google.Android.Play.Review" Version="2.0.2.1" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.Contains('net8.0-android')) ">
    <PackageReference Include="Microsoft.Maui.Essentials" Version="8.0.100" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework.Contains('net9.0-android')) ">
    <PackageReference Include="Microsoft.Maui.Essentials" Version="9.0.10" />
  </ItemGroup>
  
  <!-- Windows -->
  <ItemGroup Condition="$(TargetFramework.StartsWith('net')) == true AND $(TargetFramework.Contains('-windows')) != true">
    <Compile Remove="**\*.uwp.cs" />
    <None Include="**\*.uwp.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
    <Compile Remove="**\uwp\**\*.cs" />
    <None Include="**\uwp\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
  </ItemGroup>
  <!-- .NET (generic) -->
  <ItemGroup Condition="!($(TargetFramework.StartsWith('net')) == true AND $(TargetFramework.EndsWith('.0')) == true AND $(TargetFramework.Contains('-')) != true)">
    <!-- e.g net6.0 or net9.0 (and higher) -->
    <Compile Remove="**\*.net.cs" />
    <None Include="**\*.net.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="all" IsImplicitlyDefined="true" />
    <PackageReference Include="System.Management" Version="7.0.0" Condition="$(TargetFramework.Contains('-windows')) == true" />
  </ItemGroup>

  <!-- Package additions -->
  <ItemGroup>
    <None Include="..\..\icon.png" PackagePath="icon.png" Pack="true" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>



  
</Project>
